theme: jekyll-theme-slate
title: Questionify - Simpler questions
description: How can coding for questions be made simpler? Questionify has the answers. Questionify simplifies the code for asking and answering questions.
show_downloads: true
google_analytics: UA-72546719-7